### ISSUE TITLE
Error 400 (Bad Request)

### ISSUE THREAD

**Issue by lcx** [jpalumickas/revolut-ruby#2]
hi, I'm not really sure this is a bug or rather I'm doing something wrong and it's a cry for help but looking into the code I can't really see what's wrong. 

This is my code

```
require 'revolut'

client = Revolut::Client.new(api_key: 'oa_sand_....', environment: :sandbox)
client.accounts
```

```
2.6.3 :006 > client = Revolut::Client.new(api_key: token, environment: :sandbox)
 => #<Revolut::Client:0x00007f92a485e768 @config=#<Revolut::Configuration:0x00007f92a485e740 @api_key="oa_sand_....", @environment=:sandbox>>
2.6.3 :007 >
2.6.3 :008 > client.accounts
NOTE: Inheriting Faraday::Error::ClientError is deprecated; use Faraday::ClientError instead. It will be removed in or after version 1.0
Faraday::Error::ClientError.inherited called from /Users/cristian/.rvm/gems/ruby-2.6.3@revolut/gems/faraday_middleware-0.13.1/lib/faraday_middleware/response/follow_redirects.rb:6.
NOTE: Faraday::Error::ParsingError.new is deprecated; use Faraday::ParsingError.new instead. It will be removed in or after version 1.0
Faraday::Error::ParsingError.new called from /Users/cristian/.rvm/gems/ruby-2.6.3@revolut/gems/faraday_middleware-0.13.1/lib/faraday_middleware/response_middleware.rb:42.
Traceback (most recent call last):
       16: from /Users/cristian/.rvm/gems/ruby-2.6.3@revolut/gems/faraday-0.17.1/lib/faraday/connection.rb:138:in `get'
       15: from /Users/cristian/.rvm/gems/ruby-2.6.3@revolut/gems/faraday-0.17.1/lib/faraday/connection.rb:387:in `run_request'
       14: from /Users/cristian/.rvm/gems/ruby-2.6.3@revolut/gems/faraday-0.17.1/lib/faraday/rack_builder.rb:143:in `build_response'
       13: from /Users/cristian/.rvm/gems/ruby-2.6.3@revolut/gems/faraday_middleware-0.13.1/lib/faraday_middleware/request/encode_json.rb:24:in `call'
       12: from /Users/cristian/.rvm/gems/ruby-2.6.3@revolut/gems/faraday_middleware-0.13.1/lib/faraday_middleware/response/follow_redirects.rb:75:in `call'
       11: from /Users/cristian/.rvm/gems/ruby-2.6.3@revolut/gems/faraday_middleware-0.13.1/lib/faraday_middleware/response/follow_redirects.rb:87:in `perform_with_redirection'
       10: from /Users/cristian/.rvm/gems/ruby-2.6.3@revolut/gems/faraday-0.17.1/lib/faraday/response.rb:8:in `call'
        9: from /Users/cristian/.rvm/gems/ruby-2.6.3@revolut/gems/faraday-0.17.1/lib/faraday/response.rb:8:in `call'
        8: from /Users/cristian/.rvm/gems/ruby-2.6.3@revolut/gems/faraday_middleware-0.13.1/lib/faraday_middleware/response_middleware.rb:31:in `call'
        7: from /Users/cristian/.rvm/gems/ruby-2.6.3@revolut/gems/faraday-0.17.1/lib/faraday/response.rb:61:in `on_complete'
        6: from /Users/cristian/.rvm/gems/ruby-2.6.3@revolut/gems/faraday_middleware-0.13.1/lib/faraday_middleware/response_middleware.rb:33:in `block in call'
        5: from /Users/cristian/.rvm/gems/ruby-2.6.3@revolut/gems/faraday_middleware-0.13.1/lib/faraday_middleware/response_middleware.rb:40:in `process_response'
        4: from /Users/cristian/.rvm/gems/ruby-2.6.3@revolut/gems/faraday_middleware-0.13.1/lib/faraday_middleware/response_middleware.rb:51:in `parse'
        3: from /Users/cristian/.rvm/gems/ruby-2.6.3@revolut/gems/faraday_middleware-0.13.1/lib/faraday_middleware/response/parse_json.rb:11:in `block in <class:ParseJson>'
        2: from /Users/cristian/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/json/common.rb:156:in `parse'
        1: from /Users/cristian/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/json/common.rb:156:in `parse'
Faraday::Error::ParsingError (767: unexpected token at '<!DOCTYPE html>)
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 400 (Bad Request)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>400.</b> <ins>That’s an error.</ins>
  <p>Your client has issued a malformed or illegal request.  <ins>That’s all we know.</ins>
'
```

Doing the same via curl gives me results so it looks like the toke is working. 

```
curl https://sandbox-b2b.revolut.com/api/1.0/accounts \  
                                     -H "Authorization: Bearer oa_sand_..."
[{"id":"458dd208-5505-4c1c-afc9-e181b30cac3a","name":"Main","balance":28600,"currency":"GBP","state":"active","public":true,"created_at":"2019-12-13T15:42:01.299865Z","updated_at":"2019-12-13T15:42:01.377787Z"},{"id":"7d602165-2b68-4d1c-a6eb-fc0343c90d0f","name":"Business trips","balance":14700,"currency":"USD","state":"active","public":true,"created_at":"2019-12-13T15:42:01.299802Z","updated_at":"2019-12-13T15:42:01.380500Z"},{"id":"9fa373a3-e7bb-4a8f-a78c-7c095e45e9d7","name":"Payments","balance":5300,"currency":"AUD","state":"active","public":false,"created_at":"2019-12-13T15:42:01.375357Z","updated_at":"2019-12-13T15:42:01.375357Z"},{"id":"e84f6dba-247c-4b6c-b1c2-49c4c197d73d","name":"European suppliers","balance":3490,"currency":"EUR","state":"active","public":true,"created_at":"2019-12-13T15:42:01.299864Z","updated_at":"2019-12-13T15:42:01.379758Z"}]
```
Ruby version: ruby 2.6.3p62

My gems: 

```
bigdecimal (default: 1.4.1)
bundler (default: 1.17.2)
bundler-unload (1.0.2)
cmath (default: 1.0.0)
csv (default: 3.0.9)
date (default: 2.0.0)
dbm (default: 1.0.0)
did_you_mean (1.3.0)
e2mmap (default: 0.1.0)
etc (default: 1.0.1)
executable-hooks (1.6.0)
faraday (0.17.1)
faraday_middleware (0.13.1)
fcntl (default: 1.0.0)
fiddle (default: 1.0.0)
fileutils (default: 1.1.0)
forwardable (default: 1.2.0)
gdbm (default: 2.0.0)
gem-wrappers (1.4.0)
hashie (4.0.0)
io-console (default: 0.4.7)
ipaddr (default: 1.2.2)
irb (default: 1.0.0)
json (default: 2.1.0)
logger (default: 1.3.0)
matrix (default: 0.1.0)
minitest (5.11.3)
multipart-post (2.1.1)
mutex_m (default: 0.1.0)
net-telnet (0.2.0)
openssl (default: 2.1.2)
ostruct (default: 0.1.0)
power_assert (1.1.3)
prime (default: 0.1.0)
psych (default: 3.1.0)
rake (12.3.2)
rdoc (default: 6.1.0)
revolut (1.1.0)
rexml (default: 3.1.9)
rss (default: 0.2.7)
rubygems-bundler (1.4.5)
rvm (1.11.3.9)
scanf (default: 1.0.0)
sdbm (default: 1.0.0)
shell (default: 0.7)
stringio (default: 0.0.2)
strscan (default: 1.0.0)
sync (default: 0.5.0)
test-unit (3.2.9)
thwait (default: 0.1.0)
tracer (default: 0.1.0)
webrick (default: 1.4.2)
xmlrpc (0.3.0)
zlib (default: 1.0.0)
```

**Comment by jpalumickas** [comment]
Hey @lcx 

Thanks for reporting this issue, I think it was related to Faraday Follow redirects middleware. I removed it to fix this issue and released new 1.2.0 version. Please report if you will have more issues!

Cheers! 😉
